import { useState, useEffect, useRef } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
  FileEdit, Sparkles, Download, Trash2, Play, BarChart2, X, Building2, Calendar,
} from "lucide-react";
import { jdcreatorApi, downloadBlob } from "../lib/api";
import { useAuth } from "../hooks/useAuth";
import { useLatestMutation } from "../hooks/useLatestMutation";
import HistoryDropdown from "../components/HistoryDropdown";

function todayStr() {
  const d = new Date();
  return d.toLocaleDateString("en-GB"); // dd/mm/yyyy, matches backend issue_date format
}

export default function JDCreatorPage() {
  const { user } = useAuth();
  const qc = useQueryClient();
  const [tab, setTab] = useState<"new" | "history">("new");

  const [roleTitle, setRoleTitle] = useState("");
  const [jobType, setJobType] = useState("Full time");
  const [contractDuration, setContractDuration] = useState("6 Months");
  const [customEndDate, setCustomEndDate] = useState("");
  const [expiryDate, setExpiryDate] = useState("");
  const [skills, setSkills] = useState<string[]>([]);
  const [skillInput, setSkillInput] = useState("");
  const [experience, setExperience] = useState("");
  const [education, setEducation] = useState("");
  const [selectedId, setSelectedId] = useState<number | null>(null);

  // Latest Generate JD status/result, read from the shared mutation cache —
  // this is what makes the generation survive navigating to another agent
  // page and back: the network request keeps running regardless of which
  // component (if any) is mounted, and this hook picks up wherever it left
  // off rather than relying on local component state that gets wiped on
  // unmount.
  const genState = useLatestMutation<any>(["jd-generate"]);
  const result = genState.status === "success" ? genState.data : null;

  const { data: documents = [] } = useQuery({
    queryKey: ["jd-documents"],
    queryFn: jdcreatorApi.listDocuments,
  });

  const generateMut = useMutation({
    mutationKey: ["jd-generate"],
    mutationFn: () => jdcreatorApi.generate({
      role_title: roleTitle,
      job_type: jobType,
      contract_duration: jobType !== "Full time"
        ? (contractDuration === "Custom" ? customEndDate : contractDuration)
        : null,
      expiry_date: expiryDate,
      skills_required: skills,
      experience_required: experience,
      education_required: education,
    }),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["jd-documents"] });
    },
  });

  // Belt-and-braces: if generation finishes while the user is on a
  // different page, the mutation's own onSuccess above may never fire
  // (it's tied to this specific mount, which didn't exist when it
  // resolved). This effect instead reacts to the shared mutation cache
  // directly, so it reliably refreshes the History list and jumps the
  // dropdown to the new JD no matter when the user comes back to look.
  const lastSeenGenId = useRef<number | null>(null);
  useEffect(() => {
    if (genState.status === "success" && genState.data?.id && genState.data.id !== lastSeenGenId.current) {
      lastSeenGenId.current = genState.data.id;
      qc.invalidateQueries({ queryKey: ["jd-documents"] });
      setSelectedId(genState.data.id);
    }
  }, [genState.status, genState.data?.id, qc]);

  const deleteMut = useMutation({
    mutationFn: (id: number) => jdcreatorApi.deleteDocument(id),
    onSuccess: (_data, id) => {
      qc.invalidateQueries({ queryKey: ["jd-documents"] });
      if (selectedId === id) setSelectedId(null);
    },
  });

  const downloadMut = useMutation({
    mutationFn: (id: number) => jdcreatorApi.download(id),
    onSuccess: (blob, id) => {
      const doc = id === result?.id ? result : documents.find((d: any) => d.id === id);
      const name = (doc?.role_title || "JD").replace(/[^a-zA-Z0-9 _-]/g, "").replace(/\s+/g, "_");
      downloadBlob(blob, `JD_${name || id}.docx`);
    },
  });

  const addSkill = () => {
    const s = skillInput.trim();
    if (s && !skills.includes(s)) setSkills(prev => [...prev, s]);
    setSkillInput("");
  };
  const removeSkill = (s: string) => setSkills(prev => prev.filter(x => x !== s));

  const canGenerate = roleTitle.trim().length > 0 && genState.status !== "pending";
  const selectedDoc = documents.find((d: any) => d.id === selectedId) || null;

  const renderPreview = (doc: any) => (
    <div>
      {doc.ai_powered && (
        <div className="tiq-alert tiq-alert-success" style={{ marginBottom: 12, display: "flex", alignItems: "center", gap: 8 }}>
          <Sparkles size={13} /> AI-generated by {doc.llm_provider === "ollama" ? "Ollama (local LLM)" : doc.llm_provider === "groq" ? "Groq LLM" : "AI"}
        </div>
      )}
      <div style={{ textAlign: "center", marginBottom: 16 }}>
        <div style={{ fontWeight: 800, fontSize: 17 }}>{doc.company_name || "Company Name"}</div>
        <div style={{ fontSize: 13, color: "var(--text-muted)" }}>Position Description</div>
      </div>
      <table className="tiq-table" style={{ marginBottom: 16 }}>
        <tbody>
          <tr><td style={{ fontWeight: 700, width: 160 }}>Position Title</td><td>{doc.role_title}</td></tr>
          <tr><td style={{ fontWeight: 700 }}>Employment Type</td><td>{doc.job_type || "Full time"}</td></tr>
          {doc.job_type && doc.job_type !== "Full time" && doc.contract_duration && (
            <tr><td style={{ fontWeight: 700 }}>Contract Duration</td><td>{doc.contract_duration}</td></tr>
          )}
          <tr><td style={{ fontWeight: 700 }}>Date Issued</td><td>{doc.issue_date}</td></tr>
          <tr><td style={{ fontWeight: 700 }}>Application Deadline</td><td>{doc.expiry_date || "—"}</td></tr>
        </tbody>
      </table>

      <div style={{ fontSize: 11, fontWeight: 700, textTransform: "uppercase", color: "var(--teal-500)", marginBottom: 6 }}>Position Purpose</div>
      <p style={{ fontSize: 13, lineHeight: 1.6, color: "var(--text-secondary)", marginBottom: 16 }}>{doc.position_purpose}</p>

      {doc.organisational_context && (
        <>
          <div style={{ fontSize: 11, fontWeight: 700, textTransform: "uppercase", color: "var(--teal-500)", marginBottom: 6 }}>Organisational Context</div>
          <p style={{ fontSize: 13, lineHeight: 1.6, color: "var(--text-secondary)", marginBottom: 16 }}>{doc.organisational_context}</p>
        </>
      )}

      <div style={{ fontSize: 11, fontWeight: 700, textTransform: "uppercase", color: "var(--teal-500)", marginBottom: 6 }}>Key Responsibilities</div>
      <ul style={{ paddingLeft: 18, marginBottom: 16, fontSize: 13, color: "var(--text-secondary)" }}>
        {(doc.responsibilities || []).map((r: string, i: number) => <li key={i} style={{ marginBottom: 4 }}>{r}</li>)}
      </ul>

      {doc.required_qualifications?.length > 0 && (
        <>
          <div style={{ fontSize: 11, fontWeight: 700, textTransform: "uppercase", color: "var(--teal-500)", marginBottom: 6 }}>Required Qualifications</div>
          <ul style={{ paddingLeft: 18, marginBottom: 16, fontSize: 13, color: "var(--text-secondary)" }}>
            {doc.required_qualifications.map((r: string, i: number) => <li key={i} style={{ marginBottom: 4 }}>{r}</li>)}
          </ul>
        </>
      )}

      {doc.preferred_qualifications?.length > 0 && (
        <>
          <div style={{ fontSize: 11, fontWeight: 700, textTransform: "uppercase", color: "var(--teal-500)", marginBottom: 6 }}>Preferred Qualifications</div>
          <ul style={{ paddingLeft: 18, marginBottom: 16, fontSize: 13, color: "var(--text-secondary)" }}>
            {doc.preferred_qualifications.map((r: string, i: number) => <li key={i} style={{ marginBottom: 4 }}>{r}</li>)}
          </ul>
        </>
      )}

      {doc.skills_required?.length > 0 && (
        <>
          <div style={{ fontSize: 11, fontWeight: 700, textTransform: "uppercase", color: "var(--teal-500)", marginBottom: 6 }}>Skills Summary</div>
          <div style={{ display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 16 }}>
            {doc.skills_required.map((s: string) => (
              <span key={s} className="tiq-badge tiq-badge-teal" style={{ fontSize: 10 }}>{s}</span>
            ))}
          </div>
        </>
      )}
    </div>
  );

  return (
    <div>
      <div className="tiq-page-header" style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", flexWrap: "wrap", gap: 8 }}>
        <h1 className="tiq-page-title" style={{ display: "flex", alignItems: "center", gap: 10 }}>
          <FileEdit size={22} color="var(--teal-500)" /> JD Creator
        </h1>
        <p className="tiq-page-sub">Generate a formal, professional job description in seconds — download as Word</p>
      </div>

      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", flexWrap: "wrap", gap: 12 }}>
        <div className="tiq-tabs">
          <button className={`tiq-tab${tab === "new" ? " active" : ""}`} onClick={() => setTab("new")}>
            <Play size={12} style={{ display: "inline", marginRight: 6 }} /> New JD
          </button>
          <button className={`tiq-tab${tab === "history" ? " active" : ""}`} onClick={() => setTab("history")}>
            <BarChart2 size={12} style={{ display: "inline", marginRight: 6 }} /> History
            {documents.length > 0 && <span className="tiq-badge tiq-badge-slate" style={{ marginLeft: 8, fontSize: 10 }}>{documents.length}</span>}
          </button>
        </div>

        {tab === "history" && documents.length > 0 && (
          <div style={{ display: "flex", alignItems: "center", gap: 8, maxWidth: 420, width: "100%" }}>
            <HistoryDropdown
              value={selectedId}
              onChange={id => setSelectedId(id as number | null)}
              options={documents.map((d: any) => ({
                id: d.id,
                label: `${d.role_title} · ${d.company_name || "—"} · ${new Date(d.created_at).toLocaleDateString()}`,
              }))}
              onDelete={id => deleteMut.mutate(id as number)}
              placeholder="Select a JD…"
              confirmDeleteMessage="Delete this JD?"
            />
            {selectedId && (
              <button className="tiq-btn tiq-btn-outline tiq-btn-sm" onClick={() => downloadMut.mutate(selectedId)} disabled={downloadMut.isPending}>
                <Download size={12} /> {downloadMut.isPending ? "Preparing…" : "Word"}
              </button>
            )}
          </div>
        )}
      </div>

      {tab === "new" && (
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20, alignItems: "flex-start" }}>
          {/* Form */}
          <div className="tiq-card">
            <div className="tiq-card-title">Role Details</div>

            <div className="tiq-form-group">
              <label className="tiq-label">Role / Position Title *</label>
              <input className="tiq-input" value={roleTitle} onChange={e => setRoleTitle(e.target.value)}
                placeholder="e.g. Senior Data Architect" />
            </div>

            <div className="tiq-form-group">
              <label className="tiq-label">Job Type</label>
              <select className="tiq-input" value={jobType} onChange={e => setJobType(e.target.value)}>
                <option value="Full time">Full time</option>
                <option value="Fix term">Fix term</option>
                <option value="Contract">Contract</option>
              </select>
            </div>

            {jobType !== "Full time" && (
              <div className="tiq-form-group">
                <label className="tiq-label">
                  {jobType === "Contract" ? "Contract Duration" : "Fixed Term Duration"}
                </label>
                <select className="tiq-input" value={contractDuration} onChange={e => setContractDuration(e.target.value)}>
                  <option value="6 Months">6 Months</option>
                  <option value="12 Months">12 Months</option>
                  <option value="Custom">Custom end date…</option>
                </select>
                {contractDuration === "Custom" && (
                  <input type="date" className="tiq-input" style={{ marginTop: 8 }}
                    value={customEndDate} onChange={e => setCustomEndDate(e.target.value)} />
                )}
              </div>
            )}

            <div className="tiq-grid-2" style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>
              <div className="tiq-form-group">
                <label className="tiq-label"><Building2 size={11} style={{ display: "inline", marginRight: 4 }} />Company</label>
                <input className="tiq-input" value={user?.company || ""} disabled
                  style={{ opacity: .7 }} placeholder="Set company in Settings" />
              </div>
              <div className="tiq-form-group">
                <label className="tiq-label"><Calendar size={11} style={{ display: "inline", marginRight: 4 }} />Date Issued</label>
                <input className="tiq-input" value={todayStr()} disabled style={{ opacity: .7 }} />
              </div>
            </div>
            {!user?.company && (
              <div style={{ fontSize: 11, color: "var(--text-muted)", marginTop: -6, marginBottom: 10 }}>
                No company set — add one in Settings → Profile for it to appear on generated JDs.
              </div>
            )}

            <div className="tiq-form-group">
              <label className="tiq-label">Application Expiry Date</label>
              <input type="date" className="tiq-input" value={expiryDate} onChange={e => setExpiryDate(e.target.value)} />
            </div>

            <div className="tiq-form-group">
              <label className="tiq-label">Skills Required</label>
              <div style={{ display: "flex", gap: 6 }}>
                <input className="tiq-input" value={skillInput}
                  onChange={e => setSkillInput(e.target.value)}
                  onKeyDown={e => { if (e.key === "Enter") { e.preventDefault(); addSkill(); } }}
                  placeholder="Type a skill and press Enter" />
                <button type="button" className="tiq-btn tiq-btn-outline tiq-btn-sm" onClick={addSkill}>Add</button>
              </div>
              {skills.length > 0 && (
                <div style={{ display: "flex", flexWrap: "wrap", gap: 6, marginTop: 8 }}>
                  {skills.map(s => (
                    <span key={s} className="tiq-badge tiq-badge-teal" style={{ display: "flex", alignItems: "center", gap: 4 }}>
                      {s}
                      <X size={10} style={{ cursor: "pointer" }} onClick={() => removeSkill(s)} />
                    </span>
                  ))}
                </div>
              )}
            </div>

            <div className="tiq-form-group">
              <label className="tiq-label">Experience Required</label>
              <input className="tiq-input" value={experience} onChange={e => setExperience(e.target.value)}
                placeholder="e.g. 5+ years in a similar role" />
            </div>

            <div className="tiq-form-group">
              <label className="tiq-label">Education Required</label>
              <input className="tiq-input" value={education} onChange={e => setEducation(e.target.value)}
                placeholder="e.g. Bachelor's degree in Computer Science or related field" />
            </div>

            <button className="tiq-btn tiq-btn-primary" style={{ width: "100%", justifyContent: "center", marginTop: 4 }}
              onClick={() => generateMut.mutate()} disabled={!canGenerate}>
              {genState.status === "pending"
                ? <><span className="tiq-spinner" style={{ width: 14, height: 14, borderWidth: 2 }} /> Generating…</>
                : <><Sparkles size={14} /> Generate JD</>}
            </button>
            {genState.status === "pending" && (
              <div style={{ fontSize: 11, color: "var(--text-muted)", marginTop: 8 }}>
                This keeps running even if you switch to another page — come back here anytime to see the result.
              </div>
            )}
            {genState.status === "error" && (
              <div className="tiq-alert tiq-alert-error" style={{ marginTop: 10 }}>
                {(genState.error as any)?.response?.data?.detail || "Failed to generate JD"}
              </div>
            )}
          </div>

          {/* Preview */}
          <div className="tiq-card">
            <div className="tiq-card-title" style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
              <span>Preview</span>
              {result && (
                <button className="tiq-btn tiq-btn-primary tiq-btn-sm" onClick={() => downloadMut.mutate(result.id)} disabled={downloadMut.isPending}>
                  <Download size={12} /> {downloadMut.isPending ? "Preparing…" : "Download Word"}
                </button>
              )}
            </div>

            {genState.status === "pending" ? (
              <div className="tiq-empty">
                <span className="tiq-spinner" style={{ width: 32, height: 32, borderWidth: 3 }} />
                <div className="tiq-empty-title">Generating…</div>
                <div style={{ fontSize: 13 }}>This is still running in the background. It'll appear here as soon as it's done — feel free to switch pages in the meantime.</div>
              </div>
            ) : !result ? (
              <div className="tiq-empty">
                <FileEdit size={40} color="var(--teal-500)" style={{ opacity: .35 }} />
                <div className="tiq-empty-title">No JD generated yet</div>
                <div style={{ fontSize: 13 }}>Fill in the role details and click Generate JD.</div>
              </div>
            ) : renderPreview(result)}
          </div>
        </div>
      )}

      {tab === "history" && (
        <div className="tiq-card">
          {!selectedDoc ? (
            <div className="tiq-empty">
              <FileEdit size={40} color="var(--teal-500)" style={{ opacity: .35 }} />
              <div className="tiq-empty-title">{documents.length === 0 ? "No JDs generated yet" : "No JD selected"}</div>
              <div style={{ fontSize: 13 }}>
                {documents.length === 0
                  ? "Generate a JD from the New JD tab to see it here."
                  : "Choose a JD from the dropdown above to view its full details."}
              </div>
            </div>
          ) : renderPreview(selectedDoc)}
        </div>
      )}
    </div>
  );
}